### ISSUE TITLE
No way to set goal?

### ISSUE THREAD

**Issue by sonime** [MgAl2O4/PatMeDalamud#3]
I cannot find an option to set a headpat goal. There's the button in config to show notification when the goal is reached, but no command to do so.

**Comment by MgAl2O4** [comment]
Only purpose of option is to hide splash screen image - unfortunate naming on my part, never intended that to be editable.

Just for extra flavor and reward after reaching 5, 15, 25 and every +25 after that.

**Comment by sonime** [comment]
understandable have a good day
