### ISSUE TITLE
IPC Support

### ISSUE THREAD

**Issue by kalilistic** [MgAl2O4/PatMeDalamud#7]
hey, I had this request for integration with PlayerTrack.
https://github.com/kalilistic/PlayerTrack/issues/61

Would you be interested in adding or accepting a PR for IPC? I'd need the emote type and emoter player name + world or the actor id.

**Comment by MgAl2O4** [comment]
Sounds good - added in 1.7.0.2

provider: patMeEmoteCounter
message args: string counterDesc, ushort emoteId, string instigatorName, uint instigatorHomeworldID
